---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metrics-server
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://kubernetes-sigs.github.io/metrics-server/ # Helm chart repository URL ($ helm repo list)
    targetRevision: "3.12.2" # Version of the Helm chart
    chart: metrics-server # Name of the Helm chart
    helm:
      version: v3 # Default version
      releaseName: metrics-server
      passCredentials: false # public Helm chart
      values: |
        defaultArgs:
        - --cert-dir=/tmp
        - --kubelet-preferred-address-types=InternalIP,ExternalIP,Hostname
        - --kubelet-use-node-status-port
        - --metric-resolution=15s
        - --kubelet-insecure-tls
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - Validate=true
      - CreateNamespace=true # Because the Helm chart will create the namespace monitoring if it does not exist
      - PrunePropagationPolicy=foreground
      - PruneLast=true
