---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: apps-staging
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/nabeelaccount/simple-argocd-2.git
    targetRevision: HEAD
    path: environments/staging/apps # Specify path to apps-of-apps
  destination:
    server: https://kubernetes.default.svc # Apply to the current cluster

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - Validate=true
      - CreateNamespace=false
      - PrunePropagationPolicy=foreground
      - PruneLast=true
